name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Cháº¡y khi báº¡n push lÃªn nhÃ¡nh main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”¹ Checkout source
        uses: actions/checkout@v3

      - name: ğŸ”¹ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          # Äá»•i theo version Flutter báº¡n dÃ¹ng

      - name: ğŸ”¹ Install dependencies
        run: flutter pub get

      - name: ğŸ”¹ Build Flutter Web
        run: flutter build web --release

      - name: ğŸš€ Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
